### ISSUE TITLE
reconsider rend="keep-hyphen"

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#21]
The @rend value "keep-hyphen" was meant to mean "keep the hyphen when tokenizing", not "keep the hyphen when rendering" as it appears from a quick read. It's also misleading to use `@tei:rend` to distinguish soft and hard hyphens when these can't be distinguished by the appearance in the source document (as `@tei:rend` is meant for). Consider revising this attribute value.

An idea from Conal Tuohy is to encode a "hard" hyphen (such as in "so-called") as an actual hyphen in the source text (without the need for any XML markup around it), and a "soft" hyphen as `<lb rend="hyphen"/>` (noting that a line-break was rendered in the source document).

Better yet, wait for Council to resolve https://github.com/TEIC/TEI/issues/361 , and follow their lead!

**Comment by kshawkin** [comment]
Council has finally resolved this in P5, explicitly recommending `@force` on `<pc>`: https://github.com/TEIC/TEI/commit/589f46997c23f26b277a104fd50aebebdfbc62f2 (with a subsequent fix in https://github.com/TEIC/TEI/commit/bed6f23393ba4631f94ac98d3e2014dacbe8d204 ).

We should follow their lead.

**Comment by emylonas** [comment]
change prose in section 3.2.2 and look at adding `<pc>` back in order to use @force
(corrected so that `<pb>` becomes `<pc>` which I think was what was intended.

**Comment by emylonas** [comment]
1. Suggest changing prose to read as follows: 
   `At Level 3, if <lb>, <cb>, and <pb> elements are used, optionally distinguish uses of the hyphen with the @break and @rend attributes. At Level 4, the use of the @break and @rend attributes on these elements is mandatory if <lb>, <cb>, and <pb> elements are used.`

I'm confused about the use of `<pc>` vs. `<rend>`

**Comment by kshawkin** [comment]
We discussed during today's BPTL call and agreed that we just need to rewrite the section on hyphenation in the BPTL document to specify using `<pc>` with `@force` _and_ an appropriate milestone element when you want to indicate hyphenation.

**Comment by emylonas** [comment]
I have rewritten the prose and it looks ok, but as I've had to comment out a bunch of xi:include sections in order to run the TEI XSL, I'm not sure about all the detailed formatting, which is why  I'm not closing the ticket. 

I also have a a nagging doubt - We say the following now:
"At Level 3, If ``<lb>, <cb> and <pb>`` are used, optionally distinguish uses of the hyphen with ``<pc>`` and `@force`. At Level 4, the use of ``<pc>`` and `@force` on these elements is mandatory." 
And yet, it's possible to just use `<lb break="no">` and render with a hyphen, if that's all you want. The `<pc>` is for people who care a lot about their hyphens. even if we continue to force people to use `<pc>` in level 4, perhaps we should explain why? (good practice to keep explicit hyphenation information separate from info on line breaks.

**Comment by kshawkin** [comment]
The rewritten prose is in a local copy of the repository, right?  I don't see anything yet.

When you write "We say the following now", I think you're referring to your local copy.  The requirement for Level 4 is carried over from BPTL v. 3.0, where, as you surmised, the thinking unstated assumption was that Level 4 texts are likely to be used as the basis for republication in other formats (like ebooks), where the pagination would be different, requiring you to know how to handle various types of hyphens.  If you could make that reasoning explicit in your edits, I think that would be excellent.

**Comment by emylonas** [comment]
yes it's in my local repo. will do

**Comment by emylonas** [comment]
close with 8f236d4

**Comment by kshawkin** [comment]
During today's BPTL call, Elli asked me to review the change she committed.

**Comment by kshawkin** [comment]
Merged pull request, now closing.
