### ISSUE TITLE
taggings events

### ISSUE THREAD

**Issue by ghost** [kshawkin/Best-Practices-for-TEI-in-Libraries#24]
There should be a recommendation for tagging names of events identified in a text (in a similar fashion to persName, placeName).

**Comment by sydb** [comment]
Problem here is that TEI doesn’t have any way to do this (other than `<name type="event">`, of course). So TEI-in-Libraries does not really have any way to do this. But perhaps this should be submitted as an issue against TEI, eh?

**Comment by kshawkin** [comment]
To clarify, since P5 doesn't offer a way to do this, the BPTL workgroup would prefer to have the Technical Council consider this as a feature request (you can submit at https://github.com/TEIC/TEI/issues ) first.  If it's implemented there, we'll address in the BPTL.  If it's not, please bring it to us again: perhaps we'll create an eventName element just in the BPTL.

**Comment by lb42** [comment]
Actually I think that's backwards. If you need this element, you should define it in your ODD, test out its usefulness, document it properly, and THEN submit it to the Council for consideration! But why not use &lt;name type="event"> ?

**Comment by kshawkin** [comment]
Lou, I see your point.  I think our thinking went down this path because the BPTL has never defined elements in its customizations, so it seemed out of scope.

As for why not use `<name type="event">`, at Level 4 (where this issue would be addressed) we have said to use `<persName>` and the other specialized elements rather than `<name>`.  So there's an argument that it would be more consistent of us to create a new element rather than to recommend `<name type="event">`.  But there's also an argument that we should use `<name type="event">` for greater interoperability with other TEI documents.

**Comment by kshawkin** [comment]
In the May 2016 meeting we felt that we should leave to Council to implement in P5 first, but subsequent discussion on the ticket questions this. Andrew will try to dig up some past discussion of event tagging to share for consideration.

**Comment by arouner** [comment]
What I was recalling was a very old initiative, "XML Schemas for Historical Event Markup and Linking Project (HEML)" that is no longer active (and hasn't been for some time).  There is still a description and some links on the Cover Pages: http://xml.coverpages.org/heml.html.  And if HEML itself is no longer active, some of its work might be folded into the TEI.

**Comment by kshawkin** [comment]
Thanks for investigating.  While heml.org still exists, the material related to this early project seems to be gone, so I don't think we should worry about that any more.

So, I think we're back to deciding whether to propose a solution of our own for the BPTL or requiring the requester to propose something to the Technical Council first.  We'll discuss at a future meeting.

**Comment by emylonas** [comment]
Chapter 13.4.2 gives example of `<name type="event">` so there is a precedent for indicating events in the text. Since `<name>` has a `@ref` it can point to an eventography.

So, in BP level 4, where we discuss names, we should also add to the examples or find a way to mention, although there isn't an "eventName" you should use `<name type="event">`.

**Comment by kshawkin** [comment]
First draft of prose to add to BPTL Level 4:

> For names of entities other than persons, organizations, and places, use `<name>` with a `type` attribute containing an appropriate value, such as "event" for the name of an event.
