### ISSUE TITLE
milestones occurring at div boundaries

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#30]
In our [description of milestones in Level 4](http://www.tei-c.org/SIG/Libraries/teiinlibraries/main-driver.html#index.xml-body.1_div.4_div.2_div.5_div.6_div.7), we should say how to handle a milestone if it occurs at a div boundary.  After all, we address what happens [when a page break occurs at a div boundary](http://www.tei-c.org/SIG/Libraries/teiinlibraries/main-driver.html#index.xml-body.1_div.3_div.6).

I suggest we similarly say that the tagging of the milestone should always be within, not between, div elements.

This is a spin-off of https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/4.

**Comment by PFSchaffner** [comment]
Kevin, looking at the description of pb behavior, I wonder if it too might need expansion and clarification, and those expansions and clarifications carried over to the question of (other) milestones. The present prose says that pbs should appear within (I usually say 'tucked inside the opening of') a text division rather than between them -- but does not say what 'text division' means or whether the rule should extend to sub-div level units (e.g. l p q head opener sp table list figure) or even phrase-level elements (hi unclear). (TCP is very inconsistent on this point, though it has been moving toward excluding at least l and p from this rule.)  

More generally, the present prose takes the meaning of 'page break' as a given without attempting to define it. We (TCP) have found it necessary to say explicitly that a page break marks the _ event_ of turning a page in the normal reading sequence, and that therefore a single page may be referenced by more than one page break tag, since there are many reading sequences that compel you to turn to a subsequent or other page, then turn back to the original page (e.g. following a footnote onto the next page, then turning back to the context; or many layouts associated with tabular or multi-column arrangements). Each of those 'turnings' requires a pb tag. Not clear if  these guidelines intend to say that or not.

**Comment by PFSchaffner** [comment]
(It also doesn't say what to do with pb tags when a text division ends, followed by a series of page breaks, but no new division follows into which to tuck them.)

**Comment by kshawkin** [comment]
Comments from @PFSchaffner have been split into two other issues: #33 and #34 .

Workgroup decided that milestones, like page breaks, should always be encoded at the lowest-level div. Once #33 is implemented, we should use same improved language in [the description of milestones in Level 4](http://www.tei-c.org/SIG/Libraries/teiinlibraries/main-driver.html#index.xml-body.1_div.4_div.2_div.5_div.6_div.7).

**Comment by kshawkin** [comment]
Implemented at https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/8bfa9dd684495060ddf6c8d64078d3a60a7c8355 .
