### ISSUE TITLE
ODDs are invalid

### ISSUE THREAD

**Issue by lb42** [kshawkin/Best-Practices-for-TEI-in-Libraries#37]
I don't know whether you care about this, but I thought I should bring to your attention that the current ODD files seem to be invalid with respect to the current P5 release. I tried to validate "maindriver.odd" using oXygen and the released tei_odds.rng, and noticed the following:
- the &lt;publicationStmt> begins with an &lt;availability>: it  should begin by identifying the agency concerned e.g. &lt;;authority>DLF&lt;/authority>
- the redefinition of title@type in lib-header.odd provokes a schematron error
-  the use of &lt;att> and  &lt;gi> within schematron messages is invalid

**Comment by kshawkin** [comment]
`maindriver.odd` has a `@version` on the root element tying it to P5 1.9.1, so I believe that's why the first bullet point isn't a problem.  I'm less clear on the others but will note that this should be handled with https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/2 .

**Comment by lb42** [comment]
I dont think any software will take any notice of @version on the root element., You need @source on your schemaspec/. But anyway, two of these three problems are nothing to do with P5 schema changes, sfaics.

**Comment by sydb** [comment]
Good points. I’ll try to look into these tomorrow.

**Comment by sydb** [comment]
1. The content model of `<publicationStmt>` was fixed to more properly represent the abstract model back in version 2.6.0. So while invalid against the current TEI, and in violation of the abstract model, the use of `<availability>` as the sole child of `<publicationStmt>` was valid and common back at release 1.9.1. This should be fixed though, and I just did no in 6e63c0c. I used `<authority>TEI SIG on Libraries</authority>`; feel free to suggest something better.
2. Indeed, the `<datatype>` was missing. Back in the day `roma` didn’t care. (And I don’t recall tei_odds having a constraint to check it, either.) But it seems like an error to me anyway, so I appreciate the new test and @lb42 pointing out this failure of it. Fixed in 6e63c0c.
3. Doesn’t that suggest a bug in the schema? Surely in a TEI ODD we want to be able to use TEI phrase-level elements in describing the encoding model, whether that description happens to be in a `<tei:desc>` or a `<rngA:annotation>` or a `<sch:assert>`, no?
4. While it may well be true that no current software pays attention to `@version` of `<TEI>`, back in version 1.9.1 that was the documented method of doing what we now do with `@source`.  So that would strike me as a bug. However, we should update to use the current TEI P5 as the base P5 version, and change `@version` to `@source` when we do that.

**Comment by lb42** [comment]
Re (3) -- it may well be the case that we'd like to do that. But you can only do so (I think) if you go to the trouble of defining and then using the TEI namespace in your schematron statement (which is in the schematron namespace) . I dont think that's a bug in anything, nor has it ever been otherwise. It's just the rules of the game.

**Comment by kshawkin** [comment]
For more comparison of the BPTL header and P5, see https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/47 .

**Comment by kshawkin** [comment]
(4) is now done: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/2 .

Still need to figure out if we're doing anything about (3).  And, once we've dealt with all other issues here in this GitHub project, we should go back and repeat what Lou did initially: compare with P5.  We'll need to check that any discrepancies are intentional deviations on our part.

**Comment by sydb** [comment]
Current plan is for @sydb to post a ticket to TEI, since there is no reason for TEI to complain about what is and is not allowed in a Schematron rule — if Schematron doesn’t care, why should TEI? But some further research on what Schematron does say about non-Schematron elements is needed, first.

If TEI decides not to fix this, or takes too long, we can just take those elements out.

**Comment by sydb** [comment]
Back on 2017-02-13 I created [ticket 1582](https://github.com/TEIC/TEI/issues/1582) on the TEI for this issue. So far there has been no discussion whatsoever. I don’t know if that’s a good thing or a bad thing. :-)

**Comment by kshawkin** [comment]
During the BPTL call on 2017-05-08, Syd reported that Council has acknowledged this issue but not addressed it yet.

**Comment by emylonas** [comment]
wait until Oct 15, 2017 - if Council hasn't fixed this, then remove `<gi>` and `<att>` elements from schematron rules. Make sure ahead of time that usage is correct for ex, `persName` _element_, and `@type` _attribute_

**Comment by kshawkin** [comment]
Oct. 15 has passed, so removing the postponed label.

**Comment by sydb** [comment]
Re: last remaining issue, use of `<gi>`, `<att>`, and `<val>` is flagged as invalid by tei_odds.

Council agreed at yesterday’s conference call that it is the schema that is in error: any elements from any namespace other than Schematron’s own may appear in `<sch:assert>` or `<sch:report>`.
