### ISSUE TITLE
update "Acknowledgements"

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#57]
In preparation for a release of the next version of BPTL, we should look at the text of "Acknowledgements" and think about how to update it.

Since the text of the BPTL is so far largely intact, I think that most of this should stay, though for anyone still involved, we'll need to update affiliations that are currently marked as "formerly of".  We should also add names who have participated in the [workgroup](https://wiki.tei-c.org/index.php/Workgroup_to_revise_the_Best_Practices_for_TEI_in_Libraries) in the appropriate bulleted list, updating affiliations as needed.

**Comment by sydb** [comment]
- Add something like “version 3.0”, “version 3.1”, or “versions 3.0 & 3.1” parenthetically after people's names as appropriate.
- Add missing people.
- Instead of "formerly of" with affiliations, use:
-- a solidus between institutions if person has changed institutions
-- “(Ret.)” for those who have retired
- The “writing” section is for those who contributed to the GitHub repository (or suggested changes that someone else committed); the “planning” for those who attended one or more meetings to discuss the BPTL but did not contribute prose or schema changes.
