### ISSUE TITLE
3.9.3. ref and tag URIs

### ISSUE THREAD

**Issue by eiamjw** [kshawkin/Best-Practices-for-TEI-in-Libraries#63]
The suggested mechanism for adding standard identifier for named entities only works if there is only one entity. The example given is this one:

 `<persName ref="http://viaf.org/viaf/31995584">Emily Dickinson</persName>`

However, it might be desirable to associate more than one identifier with a person, using identifiers from different vocabularies, and this cannot be done with multiple 'ref' attributes. In the real world, no one vocabulary or aggregator of vaocabularies encompasses all people.

The following solution for multiple identifiers should perhaps also be cited:

`<person>
<persName>Emily Dickinson</persName>
<idno type="VIAF">http://viaf.org/viaf/31995584</idno>
<idno type="ISNI">http://isni.org/isni/0000000121265882</idno>
<idno type="LCCN">http://id.loc.gov/authorities/names/n79054166</idno>
<idno type="Wikidata">https://www.wikidata.org/wiki/Q4441</idno>
</person>`

**Comment by lb42** [comment]
There is an important difference between person and persName however

**Comment by eiamjw** [comment]
Actually, in my real-life example, the outer element is author, not person.

**Comment by sydb** [comment]
Yup, using multiple `<idno>`s to indicate multiple name authority records for a single named entity makes perfect sense. (It gets quite confusing if you allow multiple authors to be listed in a single `<author>` — this is one of the reasons the BPTL Guidelines specifically say one author per `<author>`). This is, of course, in the bibliographic context, since that’s where `<author>` occurs.

Note that the OP first sentence implies there are multiple entities, not multiple authority records for a single entity. That is a different case, but I think he intended the case being discussed later in the post.

@emylonas agrees. :-)

**Comment by kshawkin** [comment]
So then the suggestion is to replace

> `<persName ref="http://viaf.org/viaf/31995584">Emily Dickinson</persName>`

with a fuller example:

> `<author><persName>Emily Dickinson</persName> <idno type="VIAF">http://viaf.org/viaf/31995584</idno> <idno type="ISNI">http://isni.org/isni/0000000121265882</idno> <idno type="LCCN">http://id.loc.gov/authorities/names/n79054166</idno> <idno type="Wikidata">https://www.wikidata.org/wiki/Q4441</idno></author>`

?

**Comment by emylonas** [comment]
let's go for it. assigning to myself

**Comment by emylonas** [comment]
implemented with 7fbc5b6
