### ISSUE TITLE
Types of div in backmatter

### ISSUE THREAD

**Issue by emylonas** [kshawkin/Best-Practices-for-TEI-in-Libraries#78]
In section 3.6, Textual Divisions http://paramedic.wwp.neu.edu/~syd/temp/BPTL/2018-05-17T08/main-driver.html#index.xml-body.1_div.3_div.6 , there is one fewer element in the list on the right (back matter) than there is on the left (front matter). The table has a blank and looks funny. 

We could 
a)move the bottom 4 values up and close up the blank.
b) add a new div type, for ex. `afterword` or `addendum` and move the top 4 values down by one. 

Question: Should we add a value to balance the table? if so, which value?

**Comment by emylonas** [comment]
assigned to Kevin for feedback

**Comment by kshawkin** [comment]
It appears that there are two back-to-back tables: one containing values for front and back matter, and the second containing values for the body.  Each of these tables is arranged in two pseudo-columns—that is, the column headers are repeated twice in each table, with a blank column in between.  This was apparently done to use more of the horizontal space so users don't have to scroll as far.

However, I think this is bad practice to code the tables this way.  A user with a screen-reader is going to be confused about whether things in the same row are related.  In fact, someone without a screen reader, such as myself, was also confused about whether values in the same row are somehow related.

So I think both tables should be recoded so that there's only ever one attribute value per line.  I suggest moving the attribute values for back matter _after_ the attribute values for the body.

In addition, if there are any types of sections, such as an afterword or addendum, that haven't been addressed in the table, I think we should add them.

**Comment by emylonas** [comment]
close once guidelines have been remade and checked

**Comment by kshawkin** [comment]
We verified and then made a few more tweaks.
